#:kivy 2.3.1

<PongBall>
    size: 50, 50
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size

<PongGame>:
    canvas:
        Rectangle:
            pos: self.center_x - 5, 0
            size: 10, self.height
    Label:
        font_size: 70
        center_x: root.center_x
        top:root.top - 50
        text: "0"
    PongBall:
        id: ball
        center: self.parent.center